
MUMMER=https://github.com/mummer4/mummer/releases/download/v4.0.0rc1/mummer-4.0.0rc1.tar.gz


mummer:
	wget $(MUMMER) && \
	tar xzf mummer-4.0.0rc1.tar.gz && \
	cd mummer* && \
	./configure --prefix=`pwd` && \
	make
